1. Import the numpy package under the name np (★☆☆)
hint: import … as

2. Create a null vector of size 10 (★☆☆)
hint: np.zeros

3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
hint: array[4]

4. Create a vector with values ranging from 10 to 49 (★☆☆)
hint: arange

5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
hint: reshape

6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
hint: np.nonzero

7. Create a 3x3 identity matrix (★☆☆)
hint: np.eye

8. Create a 3x3x3 array with random values (★☆☆)
hint: np.random.random

9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
hint: min, max

10. Create a random vector of size 30 and find the mean value (★☆☆)
hint: mean

11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
hint: np.diag

12. Normalize a 5x5 random matrix (★☆☆)
hint: (x -mean)/std

13. How to find common values between two arrays? (★☆☆)
hint: np.intersect1d

14. Create a random vector of size 10 and sort it (★★☆)
hint: sort

15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
hint: argmax

16. Subtract the mean of each row of a matrix (★★☆)
hint: mean(axis=,keepdims=)

17. How to get the n largest values of an array (★★★)
Z = np.arange(10000) np.random.shuffle(Z) n = 5 hint: np.argsort | np.argpartition

18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example: 6 --> 36)
hint: np.where

In [1]:
# 1
import numpy as np

In [2]:
# 2
np.zeros((5,2)).reshape(-1)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
# 3
array = np.zeros((5,2)).reshape(-1)
array[4] = 1
array

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [4]:
#4
np.arange(10,49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [5]:
# 5. Create a 3x3 matrix with values ranging from 0 to 8
np.random.randint(0, 8, (3,3))

array([[6, 0, 5],
       [6, 0, 6],
       [3, 1, 1]])

In [6]:
# 6. Find indices of non-zero elements from [1,2,0,0,4,0]
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

In [7]:
# 7. Create a 3x3 identity matrix 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
# 8. Create a 3x3x3 array with random values 
np.random.random((3,3,3))

array([[[0.47064666, 0.59327448, 0.64837245],
        [0.07946703, 0.36364687, 0.66356602],
        [0.24506904, 0.31294102, 0.52256895]],

       [[0.31062928, 0.57610684, 0.22390274],
        [0.57454442, 0.09818962, 0.4721829 ],
        [0.91381431, 0.1427565 , 0.34769078]],

       [[0.09293569, 0.14694726, 0.79242671],
        [0.24032819, 0.99361167, 0.65065152],
        [0.15886714, 0.74303365, 0.28551707]]])

In [9]:
# 9. Create a 10x10 array with random values and find the minimum and maximum values
array = np.random.randint(0,30, (10,10))
array

array([[28, 14, 16, 27, 17, 19,  2, 24, 25,  3],
       [ 4, 21, 10,  4, 16, 27,  7, 20, 16, 19],
       [21, 15, 11, 19,  7, 19,  8, 17, 15, 25],
       [26,  2, 20, 20, 28, 23,  0, 27, 13, 16],
       [16,  9,  4, 27,  1,  0,  3,  1, 26, 25],
       [28,  5,  4, 18,  3, 14, 22,  8, 23, 10],
       [13, 21, 20, 18, 11,  7,  7,  1, 29, 26],
       [29,  3, 22,  0, 15, 17,  2, 23, 17,  0],
       [13, 14, 11,  4, 28, 25, 25,  6,  5, 22],
       [ 8,  6, 13, 26, 11, 29, 20, 15, 20, 10]])

In [10]:
np.min(array)

0

In [11]:
np.max(array)

29

In [12]:
# 10. Create a random vector of size 30 and find the mean value
array = np.random.random(30)
array

array([0.83965123, 0.97644467, 0.30245759, 0.30043075, 0.60773282,
       0.58334184, 0.79651915, 0.44356946, 0.16888273, 0.95046447,
       0.99831329, 0.13502634, 0.14374118, 0.18094155, 0.8359489 ,
       0.29055247, 0.89873541, 0.40615702, 0.62389672, 0.66135424,
       0.29135179, 0.44454122, 0.46611287, 0.48271493, 0.79027539,
       0.88800112, 0.93029218, 0.46086531, 0.36452669, 0.17071348])

In [13]:
np.mean(array)

0.5477852266297865

In [14]:
# 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
array = np.array([1,2,3,4,1])
array_2 = np.diag(array)
array_2

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 1]])

In [15]:
# 12. Normalize a 5x5 random matrix
#hint: (x -mean)/std
array = np.random.randint(0,30, (5,5))
mean = np.mean(array)
st_dev = np.std(array)
array-mean/st_dev

array([[21.50731188,  5.50731188,  7.50731188,  2.50731188,  5.50731188],
       [ 8.50731188, 20.50731188,  7.50731188,  8.50731188, 15.50731188],
       [23.50731188, 11.50731188, 16.50731188,  2.50731188, -0.49268812],
       [-1.49268812, -1.49268812, 12.50731188,  2.50731188, 13.50731188],
       [ 5.50731188, 14.50731188,  9.50731188, 24.50731188, 25.50731188]])

In [16]:
# 13. How to find common values between two arrays?
array1 = np.array([1,2,3,9,12,45])
array2 = np.array([1,2,3,19,14,32])
np.intersect1d(array1,array2)

array([1, 2, 3])

In [17]:
# 14. Create a random vector of size 10 and sort it
array = np.random.random(10)
array

array([0.50332098, 0.62944657, 0.23362012, 0.03193907, 0.20717797,
       0.11511539, 0.37860236, 0.94655763, 0.51580966, 0.88590979])

In [18]:
np.sort(array)

array([0.03193907, 0.11511539, 0.20717797, 0.23362012, 0.37860236,
       0.50332098, 0.51580966, 0.62944657, 0.88590979, 0.94655763])

In [19]:
# 15. Create random vector of size 10 and replace the maximum value by 0
array = np.random.random(10)
array

array([0.66245277, 0.75833843, 0.4179898 , 0.87487565, 0.39353832,
       0.12014331, 0.98885514, 0.02240761, 0.65070122, 0.84645263])

In [20]:
x = np.argmax(array)
x

6

In [21]:
array[x] = 0

In [22]:
array

array([0.66245277, 0.75833843, 0.4179898 , 0.87487565, 0.39353832,
       0.12014331, 0.        , 0.02240761, 0.65070122, 0.84645263])

In [23]:
# 16. Subtract the mean of each row of a matrix (★★☆)
#hint: mean(axis=,keepdims=)

array = np.array([[1,2,3,4,5], [6,7,8,9,10]])
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [24]:
array.mean(axis = 1)

array([3., 8.])

In [25]:
# 17. How to get the n largest values of an array (★★★)
# Z = np.arange(10000) np.random.shuffle(Z) n = 5 hint: np.argsort | np.argpartition

z = np.arange(10000)
z

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [26]:
np.random.shuffle(z)

In [27]:
z

array([3619, 6202, 6749, ..., 3942,  146, 9118])

In [28]:
np.argsort(z)

array([9586, 2668, 2849, ..., 1480, 1280, 2763])

In [29]:
# 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example: 6 --> 36)
#hint: np.where
array = np.random.randint(0,10, (5,3))
array

array([[0, 5, 6],
       [1, 8, 9],
       [6, 5, 5],
       [9, 4, 3],
       [8, 7, 4]])

In [30]:
array = np.where(array > 4, array**2, array)
array

array([[ 0, 25, 36],
       [ 1, 64, 81],
       [36, 25, 25],
       [81,  4,  3],
       [64, 49,  4]])