1. Import the numpy package under the name np (★☆☆)
hint: import … as

2. Create a null vector of size 10 (★☆☆)
hint: np.zeros

3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
hint: array[4]

4. Create a vector with values ranging from 10 to 49 (★☆☆)
hint: arange

5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
hint: reshape

6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
hint: np.nonzero

7. Create a 3x3 identity matrix (★☆☆)
hint: np.eye

8. Create a 3x3x3 array with random values (★☆☆)
hint: np.random.random

9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
hint: min, max

10. Create a random vector of size 30 and find the mean value (★☆☆)
hint: mean

11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
hint: np.diag

12. Normalize a 5x5 random matrix (★☆☆)
hint: (x -mean)/std

13. How to find common values between two arrays? (★☆☆)
hint: np.intersect1d

14. Create a random vector of size 10 and sort it (★★☆)
hint: sort

15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
hint: argmax

16. Subtract the mean of each row of a matrix (★★☆)
hint: mean(axis=,keepdims=)

17. How to get the n largest values of an array (★★★)
Z = np.arange(10000) np.random.shuffle(Z) n = 5 hint: np.argsort | np.argpartition

18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example: 6 --> 36)
hint: np.where

In [1]:
# 1
import numpy as np

In [2]:
# 2
np.zeros((5,2)).reshape(-1)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
# 3
array = np.zeros((5,2)).reshape(-1)
array[4] = 1
array

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [4]:
#4
np.arange(10,49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [5]:
# 5. Create a 3x3 matrix with values ranging from 0 to 8
np.random.randint(0, 8, (3,3))

array([[3, 5, 6],
       [7, 2, 0],
       [0, 0, 5]])

In [6]:
# 6. Find indices of non-zero elements from [1,2,0,0,4,0]
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

In [7]:
# 7. Create a 3x3 identity matrix 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
# 8. Create a 3x3x3 array with random values 
np.random.random((3,3,3))

array([[[0.1439762 , 0.490436  , 0.6228182 ],
        [0.30790564, 0.9810013 , 0.88842567],
        [0.7214001 , 0.21536441, 0.30047349]],

       [[0.47019396, 0.81663831, 0.79412756],
        [0.89481561, 0.55600702, 0.45014259],
        [0.97232777, 0.29581213, 0.60239173]],

       [[0.32312876, 0.34930233, 0.53322893],
        [0.83692778, 0.84914769, 0.49683816],
        [0.16128345, 0.84618899, 0.37964626]]])

In [9]:
# 9. Create a 10x10 array with random values and find the minimum and maximum values
array = np.random.randint(0,30, (10,10))
array

array([[26, 12,  0, 18, 14, 10,  4,  8, 15,  2],
       [28, 27, 28,  3,  7, 16, 29, 22, 11, 17],
       [ 5, 29, 18, 26, 24, 12, 20, 14, 24, 12],
       [16, 17, 21, 19,  9,  1, 15, 20, 22, 19],
       [18,  8, 29, 21, 15,  1, 19,  1, 14, 23],
       [11, 18,  4, 24, 15,  7, 29, 23, 24,  6],
       [20, 24, 24,  8, 28, 13, 17,  2, 10,  6],
       [ 1, 16, 10, 22, 26, 10, 12, 10, 20,  9],
       [ 2, 16, 10, 11, 23,  4,  7, 15, 12, 29],
       [14, 15, 17, 29, 15, 14, 15, 29, 28, 29]])

In [10]:
np.min(array)

0

In [11]:
np.max(array)

29

In [12]:
# 10. Create a random vector of size 30 and find the mean value
array = np.random.random(30)
array

array([0.63854243, 0.26615556, 0.85577445, 0.10089303, 0.50721842,
       0.50620482, 0.97680875, 0.89999326, 0.04242367, 0.64267228,
       0.83338406, 0.6756505 , 0.63737643, 0.3143513 , 0.02806347,
       0.34749926, 0.68223798, 0.09472251, 0.48105922, 0.12270509,
       0.30695541, 0.50867877, 0.51822056, 0.36792721, 0.63062364,
       0.2226714 , 0.48486407, 0.33886663, 0.77882557, 0.60656077])

In [13]:
np.mean(array)

0.48059768367165223

In [14]:
# 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
array = np.array([1,2,3,4,1])
array_2 = np.diag(array)
array_2

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 1]])

In [15]:
# 12. Normalize a 5x5 random matrix
#hint: (x -mean)/std
array = np.random.randint(0,30, (5,5))
mean = np.mean(array)
st_dev = np.std(array)
array-mean/st_dev

array([[26.23204056, 26.23204056, 25.23204056, 13.23204056,  3.23204056],
       [23.23204056, 23.23204056, 14.23204056,  1.23204056,  3.23204056],
       [12.23204056,  9.23204056, 20.23204056, 24.23204056,  8.23204056],
       [ 3.23204056, -0.76795944, 26.23204056, -1.76795944, 10.23204056],
       [13.23204056, 21.23204056, 26.23204056, 22.23204056, 17.23204056]])

In [16]:
# 13. How to find common values between two arrays?
array1 = np.array([1,2,3,9,12,45])
array2 = np.array([1,2,3,19,14,32])
np.intersect1d(array1,array2)

array([1, 2, 3])

In [17]:
# 14. Create a random vector of size 10 and sort it
array = np.random.random(10)
array

array([0.57444971, 0.67261663, 0.4539633 , 0.46479464, 0.39415319,
       0.16198754, 0.80913718, 0.73254766, 0.63785483, 0.26175   ])

In [18]:
np.sort(array)

array([0.16198754, 0.26175   , 0.39415319, 0.4539633 , 0.46479464,
       0.57444971, 0.63785483, 0.67261663, 0.73254766, 0.80913718])

In [19]:
# 15. Create random vector of size 10 and replace the maximum value by 0
array = np.random.random(10)
array

array([0.00987768, 0.86899459, 0.58217513, 0.67489962, 0.90380167,
       0.84804568, 0.03370596, 0.56224155, 0.19250602, 0.83944053])

In [20]:
x = np.argmax(array)
x

4

In [21]:
array[x] = 0

In [22]:
array

array([0.00987768, 0.86899459, 0.58217513, 0.67489962, 0.        ,
       0.84804568, 0.03370596, 0.56224155, 0.19250602, 0.83944053])

In [23]:
# 16. Subtract the mean of each row of a matrix (★★☆)
#hint: mean(axis=,keepdims=)

array = np.array([[1,2,3,4,5], [6,7,8,9,10]])
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [24]:
array.mean(axis = 1)

array([3., 8.])

In [25]:
# 17. How to get the n largest values of an array (★★★)
# Z = np.arange(10000) np.random.shuffle(Z) n = 5 hint: np.argsort | np.argpartition

z = np.arange(10000)
z

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [26]:
np.random.shuffle(z)

In [27]:
z

array([ 837,  881,  159, ..., 8257, 8152, 3775])

In [28]:
np.argsort(z)

array([5795, 9106,  312, ..., 1310, 7666, 1953])

In [29]:
# 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example: 6 --> 36)
#hint: np.where
array = np.random.randint(0,20, (5,3))
array

array([[15,  3, 10],
       [ 0,  1, 13],
       [ 9,  2,  8],
       [13,  6,  8],
       [ 8,  4,  5]])

In [ ]:
for i in array:
    array[i] = np.where(array[i] > 4, i**2,
                    array[i]

In [73]:
array

array([[  0,  49, 169],
       [  0,  49,   3],
       [  0,  49,   4],
       [  0,  49, 169],
       [  0,  49, 169]])